### ISSUE TITLE
Using solvent_delete error

### ISSUE THREAD

**Issue by kkivg** [ATB-UQ/PyThinFilm#8]
[INFO] - Running solvent_evaporation simulation #1
Traceback (most recent call last):
  File "/root/anaconda3/bin/pytf", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/root/anaconda3/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/root/anaconda3/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/lib/python3.11/site-packages/PyThinFilm/pytf.py", line 30, in cli
    main(config, debug)
  File "/root/anaconda3/lib/python3.11/site-packages/PyThinFilm/pytf.py", line 17, in main
    while deposition.cycle():
          ^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/lib/python3.11/site-packages/PyThinFilm/deposition.py", line 195, in cycle
    self.solvent_delete()
  File "/root/anaconda3/lib/python3.11/site-packages/PyThinFilm/deposition.py", line 561, in solvent_delete
    thresh = del_config["density_thresh"]
             ~~~~~~~~~~^^^^^^^^^^^^^^^^^^
KeyError: 'density_thresh'

**Comment by kkivg** [comment]
Additionally, what parameters can be used to fully simulate the solution deposition process described in the paper

**Comment by ssande7** [comment]
It looks like there was a mis-indentation in the [example file](https://github.com/ATB-UQ/PyThinFilm/blob/master/src/PyThinFilm/test/solvent_accel_test.yml). Reducing the indentation of the `solvent_delete` line by one should fix it, assuming your input file is based on that example (see PR #9 for the change if that's unclear). If that doesn't work, a copy of your input script would be helpful for debugging.

The simulation in the paper started with a partially evaporated film from [Lee et al.](https://doi.org/10.1021/acsami.0c08454), and the insertion/deletion protocols used are described in section 2A [here](https://doi.org/10.1063/5.0091142). The comments in the example file should help with mapping the protocol in the paper to the parameters - I'd recommend going through that process to understand them since your system may need different ones to behave well, but for the most part the parameters used are the same as in the example, except for `density_thresh` which was initially 40 atoms / nm^-3 (0.04 A^-3) and `slab_height` which was initially 12.5 nm. These were adjusted as per the paper as the surface of the film approached the substrate for final drying (you'll need to stop/restart to do this). Note that if the bottom of the slab containing deletion candidates falls below `slab_lower_limit` then the slab height will be reduced, and the number of deleted atoms adjusted proportionally (as described in the paper).
